name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install uv && uv sync --all-extras --dev
    - name: Run quality checks
      run: make quality
    - name: Run security checks
      run: make security
    - name: Run docstring checks
      run: make doc
    - name: Run complexity checks
      run: make complexity
    - name: Run tests
      run: make test
